from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import NamedTuple

from fontTools.pens import DrawingPen

class Blob:
    @classmethod
    def from_file_path(cls, filename: str | Path) -> Blob: ...

class Face:
    def __init__(self, blob: Blob | bytes | None = None, index: int = 0) -> None: ...
    @property
    def upem(self) -> int: ...

class GlyphInfo:
    @property
    def codepoint(self) -> int: ...

class GlyphPosition:
    @property
    def x_advance(self) -> int: ...
    @property
    def x_offset(self) -> int: ...
    @property
    def y_offset(self) -> int: ...

class GlyphExtents(NamedTuple):
    x_bearing: int
    y_bearing: int
    width: int
    height: int

class Buffer:
    def add_str(self, text: str, item_offset: int = 0, item_length: int = -1) -> None: ...
    def guess_segment_properties(self) -> None: ...
    @property
    def glyph_infos(self) -> list[GlyphInfo]: ...
    @property
    def glyph_positions(self) -> list[GlyphPosition] | None: ...

class Font:
    def __init__(self, face_or_font: Face | Font | None = None) -> None: ...
    def set_variations(self, variations: Mapping[str, float]) -> None: ...
    def draw_glyph_with_pen(self, gid: int, pen: DrawingPen) -> None: ...
    def get_nominal_glyph(self, unicode: int) -> int | None: ...
    def get_glyph_extents(self, gid: int) -> GlyphExtents | None: ...

def shape(
    font: Font, buffer: Buffer,
    features: Mapping[str, int | bool | Sequence[tuple[int, int, int | bool]]] | None = None,
    shapers: list[str] | None = None,
) -> None: ...
