from typing import Protocol

type Point = tuple[float, float]
type Transform = tuple[float, float, float, float, float, float]

class DrawingPen(Protocol):
    def moveTo(self, pt: Point) -> None: ...
    def lineTo(self, pt: Point) -> None: ...
    def curveTo(self, *points: Point) -> None: ...
    def qCurveTo(self, *points: Point | None) -> None: ...
    def closePath(self) -> None: ...
    def endPath(self) -> None: ...
